### PR TITLE
Fix: routing and deep linking

### LINKED ISSUE #130: React native routing and deep linking with navigator
# Description

React native routing and deep linking with navigator.
At this moment, the web React native redirect every time to the first screen in the navigator.

We want to have the possibilities to directly go this page like a Nostr profile or whatever.

# Todo
- [ ] Fix deep linking in Router.tsx
- [ ] Fix navigator routing
- [ ] Clean navigators
- [ ] Fix screens

### PR DESCRIPTION
**Pull request by bhavyagosai**
fixes #130 

- fix deep linking
- fix navigator routing
  - currently due to wrong/non working auth logic, redirection was stuck at auth
  - even if publicKey was generated, stored and retreived, it was not getting fetched properly
  - thus the code was assuming the user to not have auth and redirect to login on any link render
  - thus this logic was fixed and `retrievePublicKey` was used instead of `useAuth`
- overall code cleanup
- fixed screens

### CODE REVIEW

File: apps/mobile/src/screens/Tips/index.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const Tips: React.FC = () => {
       {selectedTab !== SelectedTab.MESSAGES && (
         <Pressable
           style={styles.createPostButton}
-          onPress={() => navigation.navigate('MainStack', {screen: 'CreateForm'})}
+          onPress={() => Linking.openURL('https://afk-community.xyz/create-form')}
```
Comment (MSghais) [inline apps/mobile/src/screens/Tips/index.tsx:53]: Why change this? I'm not sure it's needed (and not cool when you are in dev ahah).
Can you readd the navigation.navigate() one?

**Review by MSghais — CHANGES_REQUESTED** [review]

**Comment by MSghais** [comment]
Good job @bhavyagosai! If you just redo the change in the comment. Gonna merged it tomorrow
