### PR TITLE
fix: fix backend Golang

### LINKED ISSUE #79: Fix backend Golang
- [ ] Fix Backend GOlang backend
- [ ] to not use configs/backend.config.Json and configs/prod-backend.config.json
- [ ] Verify if it's answering well in the Website UI /pixel
- [ ] Check if pixel etc are correctly saved

### PR DESCRIPTION
**Pull request by EjembiEmmanuel**
Resolves #79

### CODE REVIEW

File: backend/config/backend.go [hunk 1]
```diff
@@ -1,99 +1,94 @@
...
+			NewUsernameDevnet:           "../scripts/new_username.sh",
+			ChangeUsernameDevnet:        "../scripts/change_username.sh",
+			IncreaseDayDevnet:           "../scripts/increase_day_index.sh",
+			JoinChainFactionDevnet:      "../scripts/join_chain_faction.sh",
+			JoinFactionDevnet:           "../scripts/join_faction.sh",
+			LeaveFactionDevnet:          "../scripts/leave_faction.sh",
+			AddFactionTemplateDevnet:    "../scripts/add_faction_template.sh",
+			RemoveFactionTemplateDevnet: "../scripts/remove_faction_template.sh",
+		},
+		Production: false,
```
Comment (MSghais) [inline backend/config/backend.go:82]: That's can be also a .env for the Production please env?

File: backend/core/backend.go [hunk 2]
```diff
@@ -40,7 +40,7 @@ func (b *Backend) Start(port int) {
 
 func (b *Backend) GetBackendUrl() string {
 	if b.BackendConfig.Production {
-		return "https://api.art-peace.net"
+		return "https://backend-pixel.onrender.com/"
```
Comment (MSghais) [inline backend/core/backend.go:43]: maybe we can add it as a .env? Otherwise let's go

**Review by MSghais — CHANGES_REQUESTED** [review]

**Review by MSghais — APPROVED** [review]
